---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldilocks
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: goldilocks
      repoURL: https://charts.fairwinds.com/stable
      targetRevision: 9.0.2
      helm:
        valueFiles:
          - $values/addons/goldilocks/values-base.yaml
          - $values/addons/goldilocks/values-dev.yaml
    - repoURL: https://github.com/joshuasearle/idp
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: goldilocks
