---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldilocks
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: goldilocks
    repoURL: https://charts.fairwinds.com/stable
    targetRevision: 9.0.2
    helm:
      values: |
        controller:
          flags:
            on-by-default: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: goldilocks
